### ISSUE TITLE
Cannot test code using ServiceRequestContext

### ISSUE THREAD

**Issue by bartbovendeerdt** [FabricatorsGuild/FG.ServiceFabric#3]
Currently it is not possible to test any code that uses the `ServiceRequestContext.Current` setter. This due to the fact that the custom type `ServiceRequestContext` is set on the `CallContext` using `LogicalSetData`. 

I researched this issue, and found that by letting `ServiceRequestContext` inherit from `MarshalByRefObject`, this problem goes away. Are you guys open to pull requests, or are you planning on adding this?

**Comment by FredrikGoransson** [comment]
We are certainly open to and welcomes PRs! Your suggestion sounds good, if
you send a PR I will merge it.

mån 18 dec. 2017 kl. 08:45 skrev bartbovendeerdt <notifications@github.com>:

**Comment by ErikRBergman** [comment]
It's been completely rewritten and your suggestion is included. Not committed yet though. It will be included in the next release.

**Comment by bartbovendeerdt** [comment]
Nice, thanks for the update. 👍

**Comment by ErikRBergman** [comment]
Fixed in [release-1.3.2.1](/FabricatorsGuild/FG.ServiceFabric/releases/tag/release-1.3.2.1)
